/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 009d2ee6c3e481f1a407da19d621db01)
interface __BaseEnv_Env {
	DELIVERY_MODE: "live";
	ALARM_INTERVAL_SECONDS: "60";
	DETAIL_BATCH_SIZE: "4";
	DELIVERY_BATCH_SIZE: "4";
	DELIVERY_MAX_ATTEMPTS: "10";
	MAX_STATE_OFFERS: "300";
	MIN_HEALTHY_LISTING_OFFERS: "5";
	MAX_VALID_FROM_AGE_HOURS: "36";
	RECENT_RESEND_BLOCK_HOURS: "168";
	SOLD_OUT_LOOKBACK_DAYS: "3";
	SOLD_OUT_MIN_MISSES: "2";
	SOLD_OUT_MIN_ABSENCE_MINUTES: "15";
	UOL_TELEGRAM_SHADOW: DurableObjectNamespace<import("./src/worker").UolTelegramShadow>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "UolTelegramShadow";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DELIVERY_MODE" | "ALARM_INTERVAL_SECONDS" | "DETAIL_BATCH_SIZE" | "DELIVERY_BATCH_SIZE" | "DELIVERY_MAX_ATTEMPTS" | "MAX_STATE_OFFERS" | "MIN_HEALTHY_LISTING_OFFERS" | "MAX_VALID_FROM_AGE_HOURS" | "RECENT_RESEND_BLOCK_HOURS" | "SOLD_OUT_LOOKBACK_DAYS" | "SOLD_OUT_MIN_MISSES" | "SOLD_OUT_MIN_ABSENCE_MINUTES">> {}
}
