/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4609561d93bfc5138f34ccdac60c8265)
interface __BaseEnv_Env {
	UOL_BROWSER: BrowserRun;
	DELIVERY_MODE: "live";
	ALARM_INTERVAL_SECONDS: "15";
	DETAIL_BATCH_SIZE: "4";
	DELIVERY_BATCH_SIZE: "4";
	DELIVERY_MAX_ATTEMPTS: "10";
	OPS_TICKET_GRACE_MINUTES: "3";
	OPS_ALERT_COOLDOWN_MINUTES: "360";
	IMAGE_CIRCUIT_FAILURE_THRESHOLD: "3";
	IMAGE_CIRCUIT_COOLDOWN_MINUTES: "10";
	OFFER_RETENTION_DAYS: "30";
	MAX_STATE_OFFERS: "300";
	MIN_HEALTHY_LISTING_OFFERS: "5";
	MAX_VALID_FROM_AGE_HOURS: "36";
	RECENT_RESEND_BLOCK_HOURS: "168";
	SOLD_OUT_LOOKBACK_DAYS: "3";
	SOLD_OUT_MIN_MISSES: "2";
	SOLD_OUT_MIN_ABSENCE_MINUTES: "15";
	GRUPO_COMENTARIO_ID: "-1003802235343";
	OPS_TELEGRAM_CHAT_ID: "-1003802235343";
	PUBLIC_BASE_URL: "https://uol-telegram-shadow-pilot.leosaquetto.workers.dev";
	UOL_TELEGRAM_SHADOW: DurableObjectNamespace<import("./src/worker").UolTelegramShadow>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "UolTelegramShadow";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DELIVERY_MODE" | "ALARM_INTERVAL_SECONDS" | "DETAIL_BATCH_SIZE" | "DELIVERY_BATCH_SIZE" | "DELIVERY_MAX_ATTEMPTS" | "OPS_TICKET_GRACE_MINUTES" | "OPS_ALERT_COOLDOWN_MINUTES" | "IMAGE_CIRCUIT_FAILURE_THRESHOLD" | "IMAGE_CIRCUIT_COOLDOWN_MINUTES" | "OFFER_RETENTION_DAYS" | "MAX_STATE_OFFERS" | "MIN_HEALTHY_LISTING_OFFERS" | "MAX_VALID_FROM_AGE_HOURS" | "RECENT_RESEND_BLOCK_HOURS" | "SOLD_OUT_LOOKBACK_DAYS" | "SOLD_OUT_MIN_MISSES" | "SOLD_OUT_MIN_ABSENCE_MINUTES" | "GRUPO_COMENTARIO_ID" | "OPS_TELEGRAM_CHAT_ID" | "PUBLIC_BASE_URL">> {}
}
